// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7d9RVeGojUjOYztxo56SQGY11MyYQbvw',
    appId: '1:217340150232:web:880f064cb44b27f8fdf2ad',
    messagingSenderId: '217340150232',
    projectId: 'spotter-c9716',
    authDomain: 'spotter-c9716.firebaseapp.com',
    storageBucket: 'spotter-c9716.firebasestorage.app',
    measurementId: 'G-TXZNM3FYZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMMEncp6ADAcLPcpAX6e9b__EIoFD7qIk',
    appId: '1:217340150232:android:b3e9bf38bbf9f28afdf2ad',
    messagingSenderId: '217340150232',
    projectId: 'spotter-c9716',
    storageBucket: 'spotter-c9716.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWlpGLG7zZemkkiSAgLrjjyr3zdL0fgF8',
    appId: '1:217340150232:ios:686babde2bd4d4acfdf2ad',
    messagingSenderId: '217340150232',
    projectId: 'spotter-c9716',
    storageBucket: 'spotter-c9716.firebasestorage.app',
    iosClientId: '217340150232-nj0cs7or8tbnngumjgdtrak4phhdmr5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7d9RVeGojUjOYztxo56SQGY11MyYQbvw',
    appId: '1:217340150232:web:933063bf04cc9ae1fdf2ad',
    messagingSenderId: '217340150232',
    projectId: 'spotter-c9716',
    authDomain: 'spotter-c9716.firebaseapp.com',
    storageBucket: 'spotter-c9716.firebasestorage.app',
    measurementId: 'G-6GX1ZTQ9MW',
  );
}
